<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>nour</groupId>
    <artifactId>Ghanmi_Kouki</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <exec.mainClass>nour.ghanmi_kouki.Ghanmi_Kouki</exec.mainClass>
        <sonar.organization>nekouki</sonar.organization>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>
    </properties>
        <!-- Dependencies-->
    <dependencies>
        <!-- JUnit for unit tests -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <!-- Plugins -->
    <build>
        <plugins>
            <!-- Plugin Maven for JAR -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <manifestEntries>
                        <Main-Class>nour.ghanmi_kouki.Ghanmi_Kouki</Main-Class>
                    </manifestEntries>
                    <classifier>sources</classifier> <!-- This adds a classifier to attach supplemental artifacts instead of replacing them was necessary for an error might not be though-->
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Maven Plugin for javadoc-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>javadoc</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Sonar Plugin for Analysis -->
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>3.9.0.2155</version>
                <configuration>
                    <sonar.projectKey>DhaferG_Test_mvn_automs</sonar.projectKey>
                    <sonar.login>${env.SONAR_TOKEN}</sonar.login> <!-- Remplacez par votre token -->
                </configuration>
            </plugin>
            <!-- Jacoco for test coverage-->
            <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.8.7</version>
                    <executions>
                         <execution>
                              <goals>
                              <goal>prepare-agent</goal>
                              </goals>
                         </execution>
                         <execution>
                              <id>report</id>
                              <phase>verify</phase>
                              <goals>
                              <goal>report</goal>
                              </goals>
                         </execution>
                    </executions>
               </plugin>
        </plugins>
    </build>
</project>
